/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package www.novatec.com.ve.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-03-2010
 * 
 * XDoclet definition:
 * @struts.form name="busquedaForm"
 */
public class BusquedaForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	private String numTarjeta;
	private String numAfiliado;
	private String numAutorizacion;
	private String trace;
	private String fechaTransaccion;
	private String montoTransaccion;
	private String fechaCreacionRegistro;
	private int idFolder;
	

	/*
	 * Generated Methods
	 */

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	
	
	
	
	public String getFechaCreacionRegistro() {
		return fechaCreacionRegistro;
	}




	public void setFechaCreacionRegistro(final String fechaCreacionRegistro) {
		this.fechaCreacionRegistro = fechaCreacionRegistro;
	}




	public String getNumTarjeta() {
		return numTarjeta;
	}



	public void setNumTarjeta(final String numTarjeta) {
		this.numTarjeta = numTarjeta;
	}



	public String getNumAfiliado() {
		return numAfiliado;
	}



	public void setNumAfiliado(final String numAfiliado) {
		this.numAfiliado = numAfiliado;
	}



	public String getNumAutorizacion() {
		return numAutorizacion;
	}



	public void setNumAutorizacion(final String numAutorizacion) {
		this.numAutorizacion = numAutorizacion;
	}



	public String getTrace() {
		return trace;
	}



	public void setTrace(final String trace) {
		this.trace = trace;
	}



	public String getFechaTransaccion() {
		return fechaTransaccion;
	}



	public void setFechaTransaccion(final String fechaTransaccion) {
		this.fechaTransaccion = fechaTransaccion;
	}



	public String getMontoTransaccion() {
		return montoTransaccion;
	}



	public void setMontoTransaccion(final String montoTransaccion) {
		this.montoTransaccion = montoTransaccion;
	}



	public int getIdFolder() {
		return idFolder;
	}



	public void setIdFolder(final int idFolder) {
		this.idFolder = idFolder;
	}

}