/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package www.novatec.com.ve.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-04-2010
 * 
 * XDoclet definition:
 * @struts.form name="generarForm"
 */
public class GenerarForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** idDoc property */
	private int idDoc;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	

	public int getIdDoc() {
		return idDoc;
	}


	public void setIdDoc(final int idDoc) {
		this.idDoc = idDoc;
	}	
	
}