/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package www.novatec.com.ve.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-30-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public abstract class AbstractApplicationAction extends Action {
	/*
	 * Generated Methods
	 */
	private final static Logger LOG_PANTALLA = 
		Logger.getLogger(AbstractApplicationAction.class);

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	/*
	 * Clase Abstracta que ejecuta un metodo antes de ejecutar cualquier accion
	 * usuado para seguridad y control de sesion
	 */
	public ActionForward execute(final ActionMapping mapping, final ActionForm form,
			final HttpServletRequest request, final HttpServletResponse response) {
		// TODO Auto-generated method stub
		boolean control = true;
		//final HttpSession session = request.getSession(false);
		ActionForward actionForward;
		String idSession = null;
		try {
			if(request.getSession() == null 
					& request.getSession().getAttribute("sesion")==null){
				control=false;
			}else{
				idSession = 
					request.getSession().getAttribute("sesion").toString();
			}
		} catch (Exception e) {
			// TODO: handle exception
			LOG_PANTALLA.error(e);
			control=false;
		}
		
		if(!control || idSession==null){
			actionForward = new ActionForward("/salir.do",true);
			actionForward.setName("success");
		}else{
			actionForward = executeSpecificTask(mapping, form, request, response);
		}
		return actionForward;
	}
	
	public abstract ActionForward executeSpecificTask(ActionMapping mapping, 
			ActionForm form,
			HttpServletRequest request, HttpServletResponse response);
	
}