/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package www.novatec.com.ve.action;

import java.rmi.RemoteException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.rpc.ServiceException;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import ve.com.novatec.www.novatecws.DpServicesConnectionDTO;
import ve.com.novatec.www.novatecws.DpUserDTO;
import ve.com.novatec.www.novatecws.LoginSimpleRequest;
import ve.com.novatec.www.novatecws.LoginSimpleResponse;
import ve.com.novatec.www.novatecws.Novatecws_ServiceLocator;

import www.novatec.com.ve.dto.ConexionDTO;
import www.novatec.com.ve.dto.DpFolderDTO;
import www.novatec.com.ve.form.AccesoForm;
import www.novatec.com.ve.query.Consulta;

/** 
 * MyEclipse Struts
 * Creation date: 07-30-2010
 * 
 * XDoclet definition:
 * @struts.action path="/acceso" name="accesoForm" input="/web/acceso.jsp" scope="request" validate="true"
 */
public class AccesoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	private final static Logger LOG_PANTALLA = 
		Logger.getLogger(AccesoAction.class);

	@Override
	public ActionForward execute(final ActionMapping mapping,
			final ActionForm form, final HttpServletRequest request,
			final HttpServletResponse response) {
		// TODO Auto-generated method stub
		final AccesoForm accesoForm = (AccesoForm) form;// TODO Auto-generated method stub
		
		/*
		 * Intancias del servicesConnection donde se especifica 
		 * el puerto y el ip de la connecion
		 */
		final DpServicesConnectionDTO connectionDTO = 
			new DpServicesConnectionDTO(
					ConexionDTO.getHost(
							getServlet().getInitParameter("ip docpath")), 
					ConexionDTO.getPort(
							Integer.parseInt(
									getServlet().getInitParameter("port"))));
		/*
		 * Intancia de la clase que invoca los metodos del web servcices
		 */
		final Novatecws_ServiceLocator locator = new Novatecws_ServiceLocator();
		final DpUserDTO dpUserDTO = new DpUserDTO(
				accesoForm.getLogin(),
				accesoForm.getPassword());
		final LoginSimpleRequest loginRequest = 
			new LoginSimpleRequest(dpUserDTO,connectionDTO);
		
		
		LoginSimpleResponse loginResponse = null;
		try {
			loginResponse = locator.getnovatecwsSOAP().loginSimple(loginRequest);
			
			if(loginResponse.isAcceso()){
				request.getSession(true);
				request.getSession().setAttribute("sesion", 
						request.getSession().getId());
				try {
					final List<DpFolderDTO> folderDTOs =  Consulta.consultaFolder(dpUserDTO.getName());
					request.getSession().setAttribute("idFolder",folderDTOs);
					request.getSession().setAttribute("borrado", folderDTOs.size());
				} catch (Exception e) {
					// TODO Auto-generated catch block
					LOG_PANTALLA.info(e);
				}
				request.getSession().setAttribute("user",dpUserDTO);
			}else{	
				final ActionErrors actionErrors = new ActionErrors();
				actionErrors.add("errors", new ActionMessage("acceso.accesoDenegado"));
				saveErrors(request, actionErrors);
				accesoForm.setPassword("");
				return mapping.findForward("failure");
			}
		} catch (RemoteException e) {
			// TODO Auto-generated catch block
			LOG_PANTALLA.error(e);
		} catch (ServiceException e) {
			// TODO Auto-generated catch block
			LOG_PANTALLA.error(e);
		}
		return mapping.findForward("success");
	}

}