/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package www.novatec.com.ve.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-05-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class InactividadAction extends AbstractApplicationAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward executeSpecificTask(final ActionMapping mapping, 
			final ActionForm form,
			final HttpServletRequest request, 
			final HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("success");
	}
}